# Generated by Django 2.0.5 on 2018-05-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(verbose_name='rating'),
        ),
    ]
