# Generated by Django 2.0.5 on 2018-05-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteratings', '0002_auto_20180526_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='rating'),
        ),
    ]
